export default{
    announcement:'全场6折起售',
    sliders:[
       {
        id:1,
        img_url:'/static/sliders/js-1.jpg'   //滑块图
       },
       {
        id:2,
        img_url:'/static/sliders/js-2.jpg'
       },
       {
        id:3,
        img_url:'/static/sliders/js-3.png'
       },
       {
        id:4,
        img_url:'/static/sliders/js-4.jpg'
       },
       {
        id:5,
        img_url:'/static/sliders/js-5.jpg'
       }
    ],
    latestUpdated:[
        {
          id:1,
          title:'深入浅出node.js',
          img_url:'/static/covers/node-1.jpg',
          authors:['田永强']  
        },
        {
          id:2,
          title:'node入门',
          img_url:'/static/covers/node-2.jpg',
          authors:['Manuel']
        },
        {
          id:3,
          title:'node web开发',
          img_url:'/static/covers/node-3.jpg',
          authors:['David Herron']
        },
        {
          id:4,
          title:'图解HTTP',
          img_url:'/static/covers/http-1.jpg',
          authors:['上野宣']
        },
        {
          id:5,
          title:'数据结构与算法javascript描述',
          img_url:'/static/covers/js-1.jpg',
          authors:['Michael']
        },
        {
          id:6,
          title:'web全栈开发工程师的自我修养',
          img_url:'/static/covers/js-2.jpg',
          authors:['余果']
        },
        {
          id:7,
          title:'编码',
          img_url:'/static/covers/js-3.jpg',
          authors:['charles']
        },
        {
          id:8,
          title:'linux/unix设计思想',
          img_url:'/static/covers/linux-1.jpg',
          authors:['卡兹 ']
        },
        {
          id:9,
          title:'鸟哥的linux私房菜',
          img_url:'/static/covers/linux-2.jpg',
          authors:['鸟哥']
        },
        {
          id:10,
          title:'mongDB实战',
          img_url:'/static/covers/mongdb.jpg',
          authors:['Kyle Banker']
        },
        {
          id:11,
          title:'响应式web设计',
          img_url:'/static/covers/css-1.jpg',
          authors:['Ben Frain']
        },
        {
          id:12,
          title:'sass与compass实战',
          img_url:'/static/covers/css-2.jpg',
          authors:['尼德兰']
        }
    ],
    recommended:[
        {
          id:1,
          title:'github入门与实践',
          img_url:'/static/covers/github-1.jpg',
          authors:['弘记']
        },
        {
          id:2,
          title:'超实用的javascript代码片段',
          img_url:'/static/covers/js-4.jpg',
          authors:['席新亮']
        },
        {
          id:3,
          title:'es6标准入门',
          img_url:'/static/covers/js-5.jpg',
          authors:['阮一峰']
        },
        {
          id:4,
          title:'HTML5游戏开发实战',
          img_url:'/static/covers/js-6.jpg',
          authors:['Makzan']
        },
    ]
}